apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: short-link
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: ln.hinze.dev
      http:
        paths:
          - path: /([a-zA-Z0-9]{6}$|link$)
            pathType: Prefix
            backend:
              service: 
                name: short-link-api-service
                port:
                  number: 8080
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: short-link-www-service
                port: 
                  number: 80
  tls:
    - hosts:
        - ln.hinze.dev
      secretName: short-link-tls-secret
