apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - image: jhinze/beryl-halia:latest
          name: app
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            requests:
              memory: 64Mi
              cpu: 125m
            limits:
              memory: 128Mi
              cpu: 250m
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ACCESS_TOKENS
              valueFrom:
                secretKeyRef:
                  name: access-tokens
                  key: secret
          volumeMounts:
            - name: beryl-halia-storage
              mountPath: /opt/application/resources/content
      volumes:
        - name: beryl-halia-storage
          persistentVolumeClaim:
            claimName: beryl-halia-volume-claim
      nodeSelector:
        kubernetes.io/hostname: heidi.hinze.dev
