apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - image: hazelcast/hazelcast:4.1.6
          name: hazelcast
          startupProbe:
            httpGet:
              path: /hazelcast/health
              port: 5701
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /hazelcast/health
              port: 5701
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m
          ports:
            - containerPort: 5701
              protocol: TCP
          env:
            - name: HZ_NETWORK_RESTAPI_ENABLED
              value: "true"
            - name: HZ_NETWORK_JOIN_MULTICAST_ENABLED
              value: "true"
            - name: HZ_NETWORK_JOIN_KUBERNETES_ENABLED
              value: "true"
            - name: HZ_NETWORK_JOIN_KUBERNETES_NAMESPACE
              value: "vanishing-secrets"
            - name: HZ_NETWORK_JOIN_KUBERNETES_SERVICE-NAME
              value: "hazelcast-service"
              
