apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - image: jhinze/short-link-ui:version-0.2.0
          name: ui
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
          ports:
            - containerPort: 80
              protocol: TCP
      nodeSelector:
        kubernetes.io/hostname: heidi.hinze.dev
