apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-deployment
  namespace: hinze-dev-home
  labels:
    app: hinze-dev-www
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: hinze-dev-www
  template:
    metadata:
      labels:
        app: hinze-dev-www
    spec:
      containers:
        - image: jhinze/hinze-dev-home:version-1.0.0
          name: hinze-dev-www
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
          ports:
            - containerPort: 80
              protocol: TCP
