apiVersion: v1
kind: Service
metadata:
  name: protect-email-service
  namespace: hinze-dev-home
spec:
  selector:
    app: hinze-dev-protect-email
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80