apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  revisionHistoryLimit: 2
  replicas: 1
  template:
    spec:
      containers:
        - image: postgres:12.2-alpine
          name: postgres
          readinessProbe:
            exec:
              command: ["sh", "-c", "$(printf 'psql -U %s -d %s -c ''SELECT 1''' $POSTGRES_USER $POSTGRES_DB)"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["sh", "-c", "$(printf 'psql -U %s -d %s -c ''SELECT 1''' $POSTGRES_USER $POSTGRES_DB)"]
            initialDelaySeconds: 45
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 125m
              memory: 64Mi
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pass
            - name: POSTGRES_DB
              valueFrom:
               secretKeyRef:
                 name: postgres-secret
                 key: db
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: checklist-db-volume-claim
      nodeSelector:
        kubernetes.io/hostname: justin.hinze.dev
