apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  revisionHistoryLimit: 2
  replicas: 1
  template:
    spec:
      containers:
        - image: postgres:12.2-alpine
          name: postgres
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - \"psql
                - -U
                - $POSTGRES_USER
                - -d
                - $POSTGRES_DB
                - -c
                - 'SELECT 1'\"
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - \"psql
                - -U
                - $POSTGRES_USER
                - -d
                - $POSTGRES_DB
                - -c
                - 'SELECT 1'\"
            initialDelaySeconds: 45
            timeoutSeconds: 2
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pass
            - name: POSTGRES_DB
              valueFrom:
               secretKeyRef:
                 name: postgres-secret
                 key: db
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: checklist-db-volume-claim