apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - volume.yaml
  - volume-claim.yaml
namePrefix: checklist-db-
commonLabels:
  app: checklist-db