apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - image: mariadb:10.5.2
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-db-secret
                  key: root
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: blog-volume-claim