apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - image: jhinze/short-link:version-0.2.0
          name: api
          resources:
            requests:
              memory: 192Mi
              cpu: 100m
            limits:
              memory: 320Mi
              cpu: 250m
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: RECAPTCHA_V3_SECRET
              valueFrom:
                secretKeyRef:
                  name: recaptcha-secret
                  key: secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pass
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "short-link-db-postgres.short-link"
