apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - image: jhinze/short-link:0.3.0-SNAPSHOT
          name: api
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            requests:
              memory: 32Mi
              cpu: 125m
            limits:
              memory: 128Mi
              cpu: 250m
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: RECAPTCHA_V3_SECRET
              valueFrom:
                secretKeyRef:
                  name: recaptcha-secret
                  key: secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pass
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "short-link-db-postgres.short-link"
            - name: HTTP_MAX_THREADS
              value: "50"
            - name: JAVA_ARGS
              value: "-XX:+UseSerialGC"
