apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: checklist
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: cheklist-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: checklist.hinze.dev
      http:
        paths:
          - path: /checklist-api/(.*)
            pathType: Prefix
            backend:
              service:
                name: checklist-api-service
                port: 
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: checklist-www-service
                port: 
                  number: 80
  tls:
    - hosts:
        - checklist.hinze.dev
      secretName: checklist-tls-secret
