apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: checklist
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: cheklist-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: checklist.hinze.dev
      http:
        paths:
          - path: /checklist-api/(.*)
            backend:
              serviceName: checklist-api-service
              servicePort: 80
          - path: /(.*)
            backend:
              serviceName: checklist-www-service
              servicePort: 80
  tls:
    - hosts:
        - checklist.hinze.dev
      secretName: checklist-tls-secret