apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vanishing-secrets
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: secrets.hinze.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vanishing-secrets-service
                port: 
                  number: 8080
  tls:
    - hosts:
        - secrets.hinze.dev
      secretName: secrets-hinze-tls-secret
