apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - image: jhinze/vanishing-secrets:latest
          name: app
          startupProbe:
            httpGet:
              path: /q/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /q/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            requests:
              memory: 64Mi
              cpu: 125m
            limits:
              memory: 128Mi
              cpu: 250m
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: RECAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: recaptcha-secret
                  key: secret
            - name: K8S_NAMESPACE
              value: vanishing-secrets
            - name: K8S_SERVICE
              value: hazelcast-service
