apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - image: jhinze/protect-email-api:version-1.0.1
          name: protect-email-api
          resources:
            requests:
              memory: 32Mi
              cpu: 100m
            limits:
              memory: 64Mi
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: RECAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: protect-email-secret
                  key: recaptcha-secret
            - name: PROTECTED_EMAIL
              valueFrom:
                secretKeyRef:
                  name: protect-email-secret
                  key: protected-email