apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - image: jhinze/ring-automation:version-1.0.6
          name: api
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 125m
              memory: 64Mi
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ring-refresh-token
                  key: secret
            - name: TOKEN_FILE
              value: /etc/ring/token.conf
          volumeMounts:
            - mountPath: /etc/ring
              name: ring-automation-storage
      volumes:
        - name: ring-automation-storage
          persistentVolumeClaim:
            claimName: ring-automation-volume-claim
