apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: heidi.hinze.dev
      containers:
        - image: jhinze/ring-automation:version-1.0.1
          name: api
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ring-refresh-token
                  key: secret