apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - image: jhinze/hinze-dev-home:version-1.0.1
          name: hinze-dev-www
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
          ports:
            - containerPort: 80
              protocol: TCP
      nodeSelector:
        kubernetes.io/hostname: heidi.hinze.dev