apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - auto-scaler.yaml
  - disruption-budget.yaml
namePrefix: checklist-api-
commonLabels:
  app: checklist-api
