apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - image: wordpress:5.4.0-php7.4-apache
          name: wordpress
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 2
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 750m
          env:
            - name: WORDPRESS_DB_HOST
              value: "blog-db-mariadb.blog"
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-db-secret
                  key: root
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: blog-wp-volume-claim
      nodeSelector:
        kubernetes.io/hostname: heidi.hinze.dev
