apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - volume.yaml
  - volume-claim.yaml
  - auto-scaler.yaml
  - disruption-budget.yaml
namePrefix: blog-wp-
commonLabels:
  app: blog-wp
