kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 35Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/blog/wordpress"