apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - stateful-set.yaml
  - service.yaml
  - volume.yaml
  - volume-claim.yaml
  - disruption-budget.yaml
namePrefix: photoprism-
commonLabels:
  app: photoprism