kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: originals-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 35Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: import-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 35Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 35Gi